わんこ召喚

diff --git a/.github/workflows/check_format.yml b/.github/workflows/check_format.yml
--- a/.github/workflows/check_format.yml
+++ b/.github/workflows/check_format.yml
@@ -26,6 +26,11 @@ jobs:
       - name: Prettier
         run: npm run format
 
+      - name: Lint
+        id: lint
+        run: |
+          npm run lint || echo "lint_error=true" >> $GITHUB_ENV
+
       - name: reviewdog
         if: always()
         uses: reviewdog/action-eslint@v1
