エラーチェック

diff --git a/.github/workflows/check_format.yml b/.github/workflows/check_format.yml
--- a/.github/workflows/check_format.yml
+++ b/.github/workflows/check_format.yml
@@ -33,7 +33,10 @@ jobs:
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-           npm run lint | reviewdog -reporter=github-pr-review -f=eslint || echo "lint_error=true" >> $GITHUB_ENV
+          npm run lint | reviewdog -reporter=github-pr-review -f=eslint
+          if [ $? -ne 0 ]; then
+            echo "lint_error=true" >> $GITHUB_ENV
+          fi
 
       - name: Check for changes
         id: git_status
